#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  May 14, 2020 12:38:26 PM IST  platform: Linux
set vTcl(timestamp) ""


set image_list { \
    112211_(1)_png ./Downloads/112211 (1).png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m83" -background #878787 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 817x450+259+162
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab48 \
        \
        -font {-family {DejaVu Sans} -size 13 -weight bold -slant italic -underline 1} \
        -foreground black -text {Train Details :} -background #878787 \
        -height 165 -highlightcolor black -width 400 
    vTcl:DefineAlias "$top.lab48" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Train Name :} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Train No :} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {From :} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {To :} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent58 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent58" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent59 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent59" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo60 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo60" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo91 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo91" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 10 -y 40 -width 119 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 10 -y 70 -width 114 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 10 -y 100 -width 119 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -y 130 -width 125 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 130 -y 100 -width 246 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 130 -y 130 -width 246 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo60 \
        -in $site_3_0 -x 130 -y 70 -width 247 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo91 \
        -in $site_3_0 -x 130 -y 40 -width 247 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab61 \
        \
        -font {-family {DejaVu Sans} -size 13 -weight bold -slant italic -underline 1} \
        -foreground black -text {Requirements :} -background #878787 \
        -height 95 -width 400 
    vTcl:DefineAlias "$top.lab61" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab61
    ttk::combobox $site_3_0.tCo66 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo66" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo67 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo67" "TCombobox4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab68 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Type of seat :} 
    vTcl:DefineAlias "$site_3_0.lab68" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab69 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {No of seats :} 
    vTcl:DefineAlias "$site_3_0.lab69" "Label10" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tCo66 \
        -in $site_3_0 -x 140 -y 30 -width 227 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo67 \
        -in $site_3_0 -x 140 -y 60 -width 227 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    ttk::style configure PC.TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure PC.TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure PC.TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                            Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }
                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd $top.pNo64 \
        -width 392 -height 266 -takefocus {} -style "PC.TNotebook" 
    vTcl:DefineAlias "$top.pNo64" "PNotebook1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo64 configure -style "PC.TNotebook"
    bind $top.pNo64 <Button-1> {
        _button_press
    }
    bind $top.pNo64 <ButtonRelease-1> {
        _button_release
    }
    bind $top.pNo64 <Motion> {
        _mouse_over
    }
    frame $top.pNo64.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.pNo64.t0" "PNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo64 add $top.pNo64.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image image2 \
        -compound none -underline -1 
    set site_4_0  $top.pNo64.t0
    labelframe $site_4_0.lab65 \
        \
        -font {-family {DejaVu Sans} -size 12 -weight bold -slant italic -underline 1} \
        -foreground black -text {Customer Details :} -background #878787 \
        -height 225 -width 380 
    vTcl:DefineAlias "$site_4_0.lab65" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab65
    label $site_5_0.lab70 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Name :} 
    vTcl:DefineAlias "$site_5_0.lab70" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab71 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Age :} 
    vTcl:DefineAlias "$site_5_0.lab71" "Label11" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab72 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {phone no:} 
    vTcl:DefineAlias "$site_5_0.lab72" "Label12" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab73 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Aadhar no :} 
    vTcl:DefineAlias "$site_5_0.lab73" "Label13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent74 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent74" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent75 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent75" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent76 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent76" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent77 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent77" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab78 \
        -background #878787 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Email id :} 
    vTcl:DefineAlias "$site_5_0.lab78" "Label14" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent79 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_5_0.ent79" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but82 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {View all} 
    vTcl:DefineAlias "$site_5_0.but82" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab84 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab84" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab85" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab86 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab86" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab87 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab87" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab88 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab88" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab89 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab89" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 17 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RAILWAY RESERVATION SYSTEM} 
    vTcl:DefineAlias "$site_5_0.lab90" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab70 \
        -in $site_5_0 -x 10 -y 40 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab71 \
        -in $site_5_0 -x 10 -y 70 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab72 \
        -in $site_5_0 -x 10 -y 100 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab73 \
        -in $site_5_0 -x 10 -y 130 -width 99 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent74 \
        -in $site_5_0 -x 110 -y 40 -width 226 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent75 \
        -in $site_5_0 -x 110 -y 70 -width 226 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent76 \
        -in $site_5_0 -x 110 -y 100 -width 226 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent77 \
        -in $site_5_0 -x 110 -y 130 -width 226 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab78 \
        -in $site_5_0 -x 10 -y 160 -width 89 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent79 \
        -in $site_5_0 -x 110 -y 160 -width 226 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but82 \
        -in $site_5_0 -x 240 -y 200 -width 131 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab84 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab85 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab86 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab87 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab88 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab89 \
        -in $site_5_0 -x 639 -y 89 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab90 \
        -in $site_5_0 -x 390 -y 30 -width 485 -height 105 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 10 -y 10 -width 380 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.pNo64.t1 \
        -background #878787 -highlightcolor black 
    vTcl:DefineAlias "$top.pNo64.t1" "PNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo64 add $top.pNo64.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image image2 \
        -compound none -underline -1 
    set site_4_1  $top.pNo64.t1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_1.scr80 \
        -background #222226 -height 198 -highlightcolor black -width 366 
    vTcl:DefineAlias "$site_4_1.scr80" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_4_1.scr80.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_4_1.scr80 \
        -in $site_4_1 -x 10 -y 20 -width 366 -relwidth 0 -height 198 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m83
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab92 \
        -background #878787 -borderwidth 4 \
        -font {-family {Noto Serif} -size 21 -weight bold -slant italic -underline 1} \
        -foreground $vTcl(actual_gui_fg) -text {Railway Reservation System} 
    vTcl:DefineAlias "$top.lab92" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab93 \
        -background #878787 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -image 112211_(1)_png -text Label 
    vTcl:DefineAlias "$top.lab93" "Label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 10 -y 170 -width 400 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 10 -y 340 -width 400 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.pNo64 \
        -in $top -x 420 -y 170 -width 392 -relwidth 0 -height 266 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab92 \
        -in $top -x 350 -y 50 -width 449 -relwidth 0 -height 81 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab93 \
        -in $top -x 20 -y 10 -width 319 -relwidth 0 -height 151 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

